name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: '2.0.7'

dev_dependencies:
  surf_lint_rules: ^3.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - res/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: res/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: res/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto/Roboto-Black.ttf
          weight: 900